using System;
using System.Collections.Generic;
using System.Web.UI;
using System.Web.UI.WebControls;
using MySql.Data.MySqlClient;
namespace TheRanger
{
    public partial class ClientDashboard : Page
    {
        protected void Page_Load(object sender,EventArgs e){if(!IsClient()){Response.Redirect("Login.aspx");return;}if(!IsPostBack){litName.Text=Server.HtmlEncode(Convert.ToString(Session["UserName"]));LoadDashboard();}}
        private bool IsClient(){return Session["UserRole"]!=null&&string.Equals(Session["UserRole"].ToString(),"Client",StringComparison.Ordinal);}
        private void LoadDashboard(){int clientId=Convert.ToInt32(Session["UserId"]);var bookings=new List<BookingView>();using(var con=Database.GetConnection()){con.Open();
            litAccommodationCount.Text=ExecuteCount(con,"SELECT COUNT(*) FROM Bookings WHERE client_id=@id",clientId).ToString("N0");
            litDriveCount.Text=ExecuteCount(con,"SELECT COUNT(*) FROM DriveBookings WHERE client_id=@id",clientId).ToString("N0");
            litActiveCount.Text=ExecuteCount(con,"SELECT (SELECT COUNT(*) FROM Bookings WHERE client_id=@id AND booking_status IN ('Pending','Confirmed'))+(SELECT COUNT(*) FROM DriveBookings WHERE client_id=@id AND booking_status IN ('Pending','Confirmed'))",clientId).ToString("N0");
            const string query=@"SELECT booking_id,booking_type,item_name,location,booking_status,total_amount,date_display,guests_display,booking_date FROM(SELECT b.booking_id,'Accommodation' AS booking_type,a.accommodation_name AS item_name,a.location,b.booking_status,b.total_amount,CONCAT(DATE_FORMAT(b.check_in_date,'%d %b %Y'),' - ',DATE_FORMAT(b.check_out_date,'%d %b %Y')) AS date_display,CONCAT(b.number_of_guests,' guest(s)') AS guests_display,b.booking_date FROM Bookings b INNER JOIN Accommodation a ON a.accommodation_id=b.accommodation_id WHERE b.client_id=@id UNION ALL SELECT d.drive_booking_id,'Game Drive' AS booking_type,g.drive_name AS item_name,g.location,d.booking_status,d.total_amount,DATE_FORMAT(d.drive_date,'%d %b %Y') AS date_display,CONCAT(d.number_of_guests,' guest(s)') AS guests_display,d.booking_date FROM DriveBookings d INNER JOIN GameDrive g ON g.game_drive_id=d.game_drive_id WHERE d.client_id=@id)x ORDER BY booking_date DESC";
            using(var cmd=new MySqlCommand(query,con)){cmd.Parameters.AddWithValue("@id",clientId);using(var reader=cmd.ExecuteReader())while(reader.Read())bookings.Add(new BookingView{BookingId=Convert.ToInt32(reader["booking_id"]),BookingType=Convert.ToString(reader["booking_type"]),ItemName=Convert.ToString(reader["item_name"]),Location=Convert.ToString(reader["location"]),BookingStatus=Convert.ToString(reader["booking_status"]),TotalAmount=Convert.ToDecimal(reader["total_amount"]),DateDisplay=Convert.ToString(reader["date_display"]),GuestsDisplay=Convert.ToString(reader["guests_display"])});}
        }rptBookings.DataSource=bookings;rptBookings.DataBind();pnlEmpty.Visible=bookings.Count==0;}
        private int ExecuteCount(MySqlConnection con,string sql,int id){using(var cmd=new MySqlCommand(sql,con)){cmd.Parameters.AddWithValue("@id",id);object value=cmd.ExecuteScalar();return value==null||value==DBNull.Value?0:Convert.ToInt32(value);}}
        protected void rptBookings_ItemDataBound(object sender,RepeaterItemEventArgs e){if(e.Item.ItemType!=ListItemType.Item&&e.Item.ItemType!=ListItemType.AlternatingItem)return;BookingView b=e.Item.DataItem as BookingView;if(b==null)return;((Literal)e.Item.FindControl("litBookingType")).Text=Server.HtmlEncode(b.BookingType);((Literal)e.Item.FindControl("litItemName")).Text=Server.HtmlEncode(b.ItemName);((Literal)e.Item.FindControl("litLocation")).Text=Server.HtmlEncode(b.Location);((Literal)e.Item.FindControl("litDate")).Text=Server.HtmlEncode(b.DateDisplay);((Literal)e.Item.FindControl("litGuests")).Text=Server.HtmlEncode(b.GuestsDisplay);((Literal)e.Item.FindControl("litTotal")).Text=b.TotalAmount.ToString("N2");var status=(Label)e.Item.FindControl("lblStatus");var cancel=(LinkButton)e.Item.FindControl("btnCancel");status.Text=Server.HtmlEncode(b.BookingStatus);status.CssClass="status status-"+GetStatusCss(b.BookingStatus);cancel.CommandName=b.BookingType;cancel.Visible=IsCancellable(b.BookingStatus);}
        protected void CancelBooking_Command(object sender,CommandEventArgs e){if(!IsClient()){Response.Redirect("Login.aspx");return;}int bookingId;if(!int.TryParse(Convert.ToString(e.CommandArgument),out bookingId))return;string table,idColumn;if(string.Equals(e.CommandName,"Accommodation",StringComparison.Ordinal)){table="Bookings";idColumn="booking_id";}else if(string.Equals(e.CommandName,"Game Drive",StringComparison.Ordinal)){table="DriveBookings";idColumn="drive_booking_id";}else return;using(var con=Database.GetConnection()){con.Open();string q=string.Format("UPDATE {0} SET booking_status='Cancelled' WHERE {1}=@id AND client_id=@client AND booking_status IN ('Pending','Confirmed')",table,idColumn);using(var cmd=new MySqlCommand(q,con)){cmd.Parameters.AddWithValue("@id",bookingId);cmd.Parameters.AddWithValue("@client",Convert.ToInt32(Session["UserId"]));cmd.ExecuteNonQuery();}}LoadDashboard();}
        private static bool IsCancellable(string status){return string.Equals(status,"Pending",StringComparison.OrdinalIgnoreCase)||string.Equals(status,"Confirmed",StringComparison.OrdinalIgnoreCase);}private static string GetStatusCss(string status){switch((status??"").Trim().ToLowerInvariant()){case "confirmed":return "confirmed";case "cancelled":return "cancelled";case "completed":return "completed";default:return "pending";}}
        public class BookingView{public int BookingId{get;set;}public string BookingType{get;set;}public string ItemName{get;set;}public string Location{get;set;}public string BookingStatus{get;set;}public decimal TotalAmount{get;set;}public string DateDisplay{get;set;}public string GuestsDisplay{get;set;}}
    }
}
