<%@ Page Title="Manage Bookings" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="OwnerBookings.aspx.cs" Inherits="TheRanger.OwnerBookings" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="MainContent" runat="server">
<section class="page-shell"><div class="container">
<div class="mb-4"><div class="page-kicker">GUEST RESERVATIONS</div><h1 class="page-title text-dark">Bookings &amp; Reports</h1><p class="muted">Apply filters, preview the exact matching report and download it as a Ranger-styled PDF.</p></div>
<asp:Label ID="lblMessage" runat="server" CssClass="d-block mb-3"></asp:Label>
<div class="surface p-3 mb-4"><div class="row g-2">
<div class="col-lg-3"><asp:TextBox ID="txtSearch" runat="server" CssClass="form-control" placeholder="Search guest, experience or location"></asp:TextBox></div>
<div class="col-md-4 col-lg-2"><asp:DropDownList ID="ddlType" runat="server" CssClass="form-select"><asp:ListItem Value="">All types</asp:ListItem><asp:ListItem Value="Accommodation">Accommodation</asp:ListItem><asp:ListItem Value="Game Drive">Game Drive</asp:ListItem></asp:DropDownList></div>
<div class="col-md-4 col-lg-2"><asp:DropDownList ID="ddlLocation" runat="server" CssClass="form-select"></asp:DropDownList></div>
<div class="col-md-4 col-lg-2"><asp:DropDownList ID="ddlStatus" runat="server" CssClass="form-select"><asp:ListItem Value="">All statuses</asp:ListItem><asp:ListItem>Pending</asp:ListItem><asp:ListItem>Confirmed</asp:ListItem><asp:ListItem>Cancelled</asp:ListItem><asp:ListItem>Completed</asp:ListItem></asp:DropDownList></div>
<div class="col-md-6 col-lg-1"><asp:TextBox ID="txtFrom" runat="server" TextMode="Date" CssClass="form-control" ToolTip="From booking date"></asp:TextBox></div>
<div class="col-md-6 col-lg-1"><asp:TextBox ID="txtTo" runat="server" TextMode="Date" CssClass="form-control" ToolTip="To booking date"></asp:TextBox></div>
<div class="col-lg-1 d-grid"><asp:Button ID="btnFilter" runat="server" Text="Filter" CssClass="btn btn-ranger" OnClick="btnFilter_Click" /></div></div>
<div class="d-flex flex-wrap align-items-center gap-2 mt-3"><label class="small fw-bold mb-0">Report type</label><asp:DropDownList ID="ddlReportType" runat="server" CssClass="form-select" Style="max-width:260px"><asp:ListItem Value="">All bookings</asp:ListItem><asp:ListItem Value="Accommodation">Accommodation bookings</asp:ListItem><asp:ListItem Value="Game Drive">Game drive bookings</asp:ListItem><asp:ListItem Value="Pending">Pending bookings</asp:ListItem><asp:ListItem Value="Confirmed">Confirmed bookings</asp:ListItem><asp:ListItem Value="Completed">Completed bookings</asp:ListItem><asp:ListItem Value="Cancelled">Cancelled bookings</asp:ListItem></asp:DropDownList><asp:Button ID="btnPreviewReport" runat="server" Text="Preview Report" CssClass="btn btn-ranger rounded-pill" OnClick="btnPreviewReport_Click" /><asp:Button ID="btnClearFilters" runat="server" Text="Clear filters" CssClass="btn btn-outline-secondary rounded-pill" OnClick="btnClearFilters_Click" /></div></div>

<div class="surface table-ranger"><div class="d-flex justify-content-between align-items-center p-3 border-bottom"><div><strong>Filtered bookings</strong><div class="small muted">Only records matching the filters are displayed.</div></div><span class="badge-soft"><asp:Literal ID="litResultCount" runat="server">0</asp:Literal> result(s)</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Guest</th><th>Experience</th><th>Date</th><th>Guests</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody><asp:Repeater ID="rptBookings" runat="server"><ItemTemplate><tr><td><strong><%# Eval("client_name") %></strong><div class="small muted"><%# Eval("email") %></div></td><td><span class="badge-soft"><%# Eval("booking_type") %></span><div class="mt-1"><%# Eval("item_name") %></div><div class="small muted"><%# Eval("location") %></div></td><td><%# Eval("date_display") %><div class="small muted">Booked <%# Eval("booking_date_display") %></div></td><td><%# Eval("number_of_guests", "{0:N0}") %></td><td>R <%# Eval("total_amount","{0:N2}") %></td><td><asp:DropDownList ID="ddlRowStatus" runat="server" CssClass="form-select form-select-sm" SelectedValue='<%# Eval("booking_status") %>'><asp:ListItem>Pending</asp:ListItem><asp:ListItem>Confirmed</asp:ListItem><asp:ListItem>Cancelled</asp:ListItem><asp:ListItem>Completed</asp:ListItem></asp:DropDownList></td><td><asp:LinkButton ID="btnUpdate" runat="server" CssClass="btn btn-sm btn-ranger" CommandArgument='<%# Eval("booking_id") + "|" + Eval("booking_type") %>' OnCommand="Update_Command">Update</asp:LinkButton></td></tr></ItemTemplate></asp:Repeater></tbody></table></div><asp:Panel ID="pnlEmpty" runat="server" Visible="false" CssClass="p-5 text-center"><h4 class="font-display">No bookings match your filters</h4><p class="muted">Change the filters and try again.</p></asp:Panel></div>

<asp:Panel ID="pnlReportPreview" runat="server" Visible="false" CssClass="surface p-4 mt-4"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-3"><div><div class="page-kicker">REPORT PREVIEW</div><h2 class="font-display mb-1"><asp:Literal ID="litReportTitle" runat="server" /></h2><p class="muted mb-0">This preview contains only the current filtered results.</p></div><div class="d-flex gap-2"><asp:Button ID="btnDownloadPdf" runat="server" Text="Download PDF" CssClass="btn btn-ranger rounded-pill" OnClick="btnDownloadPdf_Click" /></div></div><div class="row g-3 mb-4"><div class="col-md-6"><div class="stat-box"><div class="muted small">Matching bookings</div><div class="value"><asp:Literal ID="litPreviewCount" runat="server">0</asp:Literal></div></div></div><div class="col-md-6"><div class="stat-box"><div class="muted small">Filtered total</div><div class="value">R <asp:Literal ID="litPreviewTotal" runat="server">0.00</asp:Literal></div></div></div></div><div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>Guest</th><th>Type / Experience</th><th>Location</th><th>Date</th><th>Guests</th><th>Total</th><th>Status</th></tr></thead><tbody><asp:Repeater ID="rptPreview" runat="server"><ItemTemplate><tr><td><%# Eval("booking_id") %></td><td><%# Eval("client_name") %></td><td><%# Eval("booking_type") %><div class="small muted"><%# Eval("item_name") %></div></td><td><%# Eval("location") %></td><td><%# Eval("date_display") %></td><td><%# Eval("number_of_guests","{0:N0}") %></td><td>R <%# Eval("total_amount","{0:N2}") %></td><td><%# Eval("booking_status") %></td></tr></ItemTemplate></asp:Repeater></tbody></table></div><asp:Panel ID="pnlEmptyPreview" runat="server" Visible="false" CssClass="alert alert-warning mb-0">No report rows match the selected filters.</asp:Panel></asp:Panel>
</div></section>
</asp:Content>
