using System;
using System.Collections.Generic;
using System.IO;
using MySql.Data.MySqlClient;
using System.Web.UI.WebControls;
namespace TheRanger
{
 public partial class OwnerAccommodation:System.Web.UI.Page
 {
  int owner{get{return Convert.ToInt32(Session["UserId"]);}}
  protected void Page_Load(object s,EventArgs e){if(!IsOwner()){Response.Redirect("Login.aspx");return;}if(!IsPostBack){LoadLocations();LoadImages();int id;if(int.TryParse(Request.QueryString["edit"],out id))LoadEdit(id);LoadData();}}
  bool IsOwner(){return Session["UserRole"]!=null&&Session["UserRole"].ToString()=="Owner";}
  void LoadLocations(){string selected=ddlLocation.SelectedValue;ddlLocation.Items.Clear();ddlLocation.Items.Add(new ListItem("Select existing location",""));using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT DISTINCT location FROM Accommodation WHERE location IS NOT NULL AND TRIM(location)<>'' ORDER BY location",c))using(var r=cmd.ExecuteReader())while(r.Read())ddlLocation.Items.Add(new ListItem(r[0].ToString(),r[0].ToString()));}if(ddlLocation.Items.FindByValue(selected)!=null)ddlLocation.SelectedValue=selected;}
  void LoadImages(){string selected=ddlImage.SelectedValue;ddlImage.Items.Clear();ddlImage.Items.Add(new ListItem("Auto / use matching image",""));foreach(string image in ImageHelper.ExistingImages("Images",false))ddlImage.Items.Add(new ListItem(Path.GetFileName(image),image));if(ddlImage.Items.FindByValue(selected)!=null)ddlImage.SelectedValue=selected;}
  void LoadData(){var list=new List<Item>();using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT accommodation_id,accommodation_name,location,room_type,price_per_night,max_guests,available FROM Accommodation WHERE owner_id=@o ORDER BY accommodation_id DESC",c)){cmd.Parameters.AddWithValue("@o",owner);using(var r=cmd.ExecuteReader())while(r.Read())list.Add(new Item{accommodation_id=Convert.ToInt32(r["accommodation_id"]),accommodation_name=r["accommodation_name"].ToString(),location=r["location"].ToString(),room_type=r["room_type"].ToString(),price_per_night=Convert.ToDecimal(r["price_per_night"]),max_guests=Convert.ToInt32(r["max_guests"]),available=Convert.ToBoolean(r["available"])});}}rptItems.DataSource=list;rptItems.DataBind();}
  void LoadEdit(int id){using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT * FROM Accommodation WHERE accommodation_id=@id AND owner_id=@o",c)){cmd.Parameters.AddWithValue("@id",id);cmd.Parameters.AddWithValue("@o",owner);using(var r=cmd.ExecuteReader()){if(!r.Read())return;hfId.Value=id.ToString();litFormTitle.Text="Edit accommodation";txtName.Text=r["accommodation_name"].ToString();txtDescription.Text=r["description"].ToString();txtNewLocation.Text="";txtRoom.Text=r["room_type"].ToString();txtPrice.Text=r["price_per_night"].ToString();txtMax.Text=r["max_guests"].ToString();chkAvailable.Checked=Convert.ToBoolean(r["available"]);string loc=r["location"].ToString();if(ddlLocation.Items.FindByValue(loc)!=null)ddlLocation.SelectedValue=loc;string img=Convert.ToString(r["image_path"]);if(ddlImage.Items.FindByValue(img)!=null)ddlImage.SelectedValue=img;}}}}
  protected void btnSave_Click(object s,EventArgs e){string location=string.IsNullOrWhiteSpace(txtNewLocation.Text)?ddlLocation.SelectedValue:txtNewLocation.Text.Trim();if(string.IsNullOrWhiteSpace(txtName.Text)||string.IsNullOrWhiteSpace(location)||string.IsNullOrWhiteSpace(txtRoom.Text)){Err("Name, location and room type are required.");return;}decimal price;int max;if(!decimal.TryParse(txtPrice.Text,out price)||price<=0||!int.TryParse(txtMax.Text,out max)||max<=0){Err("Enter a valid price and guest capacity.");return;}string imagePath=ddlImage.SelectedValue;if(fuImage.HasFile){string ext=Path.GetExtension(fuImage.FileName).ToLowerInvariant();string[] allowed={".jpg",".jpeg",".png",".webp",".avif"};if(Array.IndexOf(allowed,ext)<0){Err("Please upload JPG, PNG, WEBP or AVIF images only.");return;}string fileName="accommodation-"+Guid.NewGuid().ToString("N")+ext;string physical=Server.MapPath("~/Images/"+fileName);fuImage.SaveAs(physical);imagePath="Images/"+fileName;}
   using(var c=Database.GetConnection()){c.Open();bool edit;int id;edit=int.TryParse(hfId.Value,out id);string q=edit?"UPDATE Accommodation SET accommodation_name=@n,description=@d,location=@l,room_type=@r,price_per_night=@p,max_guests=@m,available=@a,image_path=@img WHERE accommodation_id=@id AND owner_id=@o":"INSERT INTO Accommodation(owner_id,accommodation_name,description,location,room_type,price_per_night,max_guests,available,image_path) VALUES(@o,@n,@d,@l,@r,@p,@m,@a,@img)";using(var cmd=new MySqlCommand(q,c)){cmd.Parameters.AddWithValue("@o",owner);cmd.Parameters.AddWithValue("@n",txtName.Text.Trim());cmd.Parameters.AddWithValue("@d",txtDescription.Text.Trim());cmd.Parameters.AddWithValue("@l",location);cmd.Parameters.AddWithValue("@r",txtRoom.Text.Trim());cmd.Parameters.AddWithValue("@p",price);cmd.Parameters.AddWithValue("@m",max);cmd.Parameters.AddWithValue("@a",chkAvailable.Checked);cmd.Parameters.AddWithValue("@img",string.IsNullOrWhiteSpace(imagePath)?(object)DBNull.Value:imagePath);if(edit)cmd.Parameters.AddWithValue("@id",id);cmd.ExecuteNonQuery();}}
   Clear();LoadLocations();LoadImages();LoadData();}
  protected void Delete_Command(object s,CommandEventArgs e){using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("DELETE FROM Accommodation WHERE accommodation_id=@id AND owner_id=@o",c)){cmd.Parameters.AddWithValue("@id",Convert.ToInt32(e.CommandArgument));cmd.Parameters.AddWithValue("@o",owner);try{cmd.ExecuteNonQuery();}catch{Err("This accommodation has bookings and cannot be deleted. Hide it instead.");}}}LoadData();}
  protected void btnCancelEdit_Click(object s,EventArgs e){Clear();}
  void Clear(){hfId.Value="";litFormTitle.Text="Add accommodation";txtName.Text=txtDescription.Text=txtNewLocation.Text=txtRoom.Text=txtPrice.Text=txtMax.Text="";chkAvailable.Checked=true;if(ddlLocation.Items.Count>0)ddlLocation.SelectedIndex=0;if(ddlImage.Items.Count>0)ddlImage.SelectedIndex=0;}
  void Err(string x){lblMessage.CssClass="alert alert-danger d-block";lblMessage.Text=Server.HtmlEncode(x);}
  class Item{public int accommodation_id{get;set;}public string accommodation_name{get;set;}public string location{get;set;}public string room_type{get;set;}public decimal price_per_night{get;set;}public int max_guests{get;set;}public bool available{get;set;}}
 }
}
