using System;
using System.Collections.Generic;
using System.IO;
using MySql.Data.MySqlClient;
using System.Web.UI.WebControls;
namespace TheRanger
{
 public partial class OwnerGameDrives:System.Web.UI.Page
 {
  int owner{get{return Convert.ToInt32(Session["UserId"]);}}
  protected void Page_Load(object s,EventArgs e){if(!IsOwner()){Response.Redirect("Login.aspx");return;}if(!IsPostBack){LoadLocations();LoadImages();int id;if(int.TryParse(Request.QueryString["edit"],out id))LoadEdit(id);LoadData();}}
  bool IsOwner(){return Session["UserRole"]!=null&&Session["UserRole"].ToString()=="Owner";}
  void LoadLocations(){string selected=ddlLocation.SelectedValue;ddlLocation.Items.Clear();ddlLocation.Items.Add(new ListItem("Select existing location",""));using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT DISTINCT location FROM GameDrive WHERE location IS NOT NULL AND TRIM(location)<>'' ORDER BY location",c))using(var r=cmd.ExecuteReader())while(r.Read())ddlLocation.Items.Add(new ListItem(r[0].ToString(),r[0].ToString()));}if(ddlLocation.Items.FindByValue(selected)!=null)ddlLocation.SelectedValue=selected;}
  void LoadImages(){string selected=ddlImage.SelectedValue;ddlImage.Items.Clear();ddlImage.Items.Add(new ListItem("Auto / use matching image",""));foreach(string image in ImageHelper.ExistingImages("Images",true))ddlImage.Items.Add(new ListItem(Path.GetFileName(image),image));if(ddlImage.Items.FindByValue(selected)!=null)ddlImage.SelectedValue=selected;}
  void LoadData(){var list=new List<Item>();using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT game_drive_id,drive_name,location,duration_hours,price,max_guests,available FROM GameDrive WHERE owner_id=@o ORDER BY game_drive_id DESC",c)){cmd.Parameters.AddWithValue("@o",owner);using(var r=cmd.ExecuteReader())while(r.Read())list.Add(new Item{game_drive_id=Convert.ToInt32(r["game_drive_id"]),drive_name=r["drive_name"].ToString(),location=r["location"].ToString(),duration_hours=Convert.ToDecimal(r["duration_hours"]),price=Convert.ToDecimal(r["price"]),max_guests=Convert.ToInt32(r["max_guests"]),available=Convert.ToBoolean(r["available"])});}}rptItems.DataSource=list;rptItems.DataBind();}
  void LoadEdit(int id){using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("SELECT * FROM GameDrive WHERE game_drive_id=@id AND owner_id=@o",c)){cmd.Parameters.AddWithValue("@id",id);cmd.Parameters.AddWithValue("@o",owner);using(var r=cmd.ExecuteReader()){if(!r.Read())return;hfId.Value=id.ToString();litFormTitle.Text="Edit game drive";txtName.Text=r["drive_name"].ToString();txtDescription.Text=r["description"].ToString();txtNewLocation.Text="";txtDuration.Text=r["duration_hours"].ToString();txtPrice.Text=r["price"].ToString();txtMax.Text=r["max_guests"].ToString();chkAvailable.Checked=Convert.ToBoolean(r["available"]);string loc=r["location"].ToString();if(ddlLocation.Items.FindByValue(loc)!=null)ddlLocation.SelectedValue=loc;string img=Convert.ToString(r["image_path"]);if(ddlImage.Items.FindByValue(img)!=null)ddlImage.SelectedValue=img;}}}}
  protected void btnSave_Click(object s,EventArgs e){string location=string.IsNullOrWhiteSpace(txtNewLocation.Text)?ddlLocation.SelectedValue:txtNewLocation.Text.Trim();if(string.IsNullOrWhiteSpace(txtName.Text)||string.IsNullOrWhiteSpace(location)){Err("Name and location are required.");return;}decimal hours,price;int max;if(!decimal.TryParse(txtDuration.Text,out hours)||hours<=0||!decimal.TryParse(txtPrice.Text,out price)||price<=0||!int.TryParse(txtMax.Text,out max)||max<=0){Err("Enter valid duration, price and guest capacity.");return;}string imagePath=ddlImage.SelectedValue;if(fuImage.HasFile){string ext=Path.GetExtension(fuImage.FileName).ToLowerInvariant();string[] allowed={".jpg",".jpeg",".png",".webp",".avif"};if(Array.IndexOf(allowed,ext)<0){Err("Please upload JPG, PNG, WEBP or AVIF images only.");return;}string fileName="gamedrive-"+Guid.NewGuid().ToString("N")+ext;fuImage.SaveAs(Server.MapPath("~/Images/"+fileName));imagePath="Images/"+fileName;}
   using(var c=Database.GetConnection()){c.Open();bool edit;int id;edit=int.TryParse(hfId.Value,out id);string q=edit?"UPDATE GameDrive SET drive_name=@n,description=@d,location=@l,duration_hours=@h,price=@p,max_guests=@m,available=@a,image_path=@img WHERE game_drive_id=@id AND owner_id=@o":"INSERT INTO GameDrive(owner_id,drive_name,description,location,duration_hours,price,max_guests,available,image_path) VALUES(@o,@n,@d,@l,@h,@p,@m,@a,@img)";using(var cmd=new MySqlCommand(q,c)){cmd.Parameters.AddWithValue("@o",owner);cmd.Parameters.AddWithValue("@n",txtName.Text.Trim());cmd.Parameters.AddWithValue("@d",txtDescription.Text.Trim());cmd.Parameters.AddWithValue("@l",location);cmd.Parameters.AddWithValue("@h",hours);cmd.Parameters.AddWithValue("@p",price);cmd.Parameters.AddWithValue("@m",max);cmd.Parameters.AddWithValue("@a",chkAvailable.Checked);cmd.Parameters.AddWithValue("@img",string.IsNullOrWhiteSpace(imagePath)?(object)DBNull.Value:imagePath);if(edit)cmd.Parameters.AddWithValue("@id",id);cmd.ExecuteNonQuery();}}
   Clear();LoadLocations();LoadImages();LoadData();}
  protected void Delete_Command(object s,CommandEventArgs e){using(var c=Database.GetConnection()){c.Open();using(var cmd=new MySqlCommand("DELETE FROM GameDrive WHERE game_drive_id=@id AND owner_id=@o",c)){cmd.Parameters.AddWithValue("@id",Convert.ToInt32(e.CommandArgument));cmd.Parameters.AddWithValue("@o",owner);try{cmd.ExecuteNonQuery();}catch{Err("This drive has bookings and cannot be deleted. Hide it instead.");}}}LoadData();}
  protected void btnClear_Click(object s,EventArgs e){Clear();}
  void Clear(){hfId.Value="";litFormTitle.Text="Add game drive";txtName.Text=txtDescription.Text=txtNewLocation.Text=txtDuration.Text=txtPrice.Text=txtMax.Text="";chkAvailable.Checked=true;if(ddlLocation.Items.Count>0)ddlLocation.SelectedIndex=0;if(ddlImage.Items.Count>0)ddlImage.SelectedIndex=0;}
  void Err(string x){lblMessage.CssClass="alert alert-danger d-block";lblMessage.Text=Server.HtmlEncode(x);}
  class Item{public int game_drive_id{get;set;}public int max_guests{get;set;}public string drive_name{get;set;}public string location{get;set;}public decimal duration_hours{get;set;}public decimal price{get;set;}public bool available{get;set;}}
 }
}
